services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: BookShope
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_bd:/docker-entrypoint-initdb.d